Add form
yiwiy9/wedding-invitation pull request #2
Opened 2023-02-05 17:18 UTC by fumiya-iwai

- エラーは出てない状態
- フォームにスタイル付けた（自分のできる限りキレイに）
  - タイトル部分、背景、ラジオボタンとか手抜きになってる
- こんなんいる？（参考の招待状にあった機能）
  - 送信内容確認画面を挟んでから送信、もしくは挟まずに送信完了のモーダルウィンドウ
  - 子供の削除確認のモーダルウィンドウ
  - 親が出席の時のみ、子供追加できる
  - 子供の人数の上限

2023-02-08 15:18 UTC, yiwiy9 commented
> 送信内容確認画面を挟んでから送信、もしくは挟まずに送信完了のモーダルウィンドウ

送信完了ページは作って欲しい（よくあるメールを送りました的な）

> 子供の削除確認のモーダルウィンドウ

これは後回しでええわ

> 親が出席の時のみ、子供追加できる

これ入れて欲しい

> 子供の人数の上限

10で

あと、childrenのエラーについてやけど、APIから返すエラーに関しては配列になってない（他項目と同じで１次元）から下のコードを適当なところに配置しておいて

```ts
{errors.children?.message && <p>{errors.children.message}</p>}
```

2023-02-11 08:37 UTC, yiwiy9 requested changes
取り急ぎこれだけ頼むわ
他の変更中がなければ、この修正終わったら`main`に入れるわ

2023-02-11 08:37 UTC, yiwiy9 commented on frontend/src/routes/main-form.tsx
> +  const { register, errors } = props
これあんま好きじゃないから
```ts
const MainForm: FC<MainProps> = ({ register, errors }) => {
```
で頼むわ

2023-02-11 08:37 UTC, yiwiy9 commented on frontend/src/routes/children-form.tsx
> +  const { register, errors, childrenIndex, removeChildren, isLoading } = props
これも同じ

2023-02-11 13:33 UTC, fumiya-iwai commented
急ぎの変更点を変えた、確認よろしく

2023-02-12 06:11 UTC, yiwiy9 approved these changes

2023-02-12 06:11 UTC, merged