Add address suggestion from zipcode
yiwiy9/wedding-invitation pull request #3
Opened 2023-02-12 19:14 UTC by fumiya-iwai

住所のサジェストが形になったが、これでどうかな。
質問一つ
- 無効な郵便番号で検索した場合のエラーはどう表示するのがベスト？（今は何もしてない）

あと直すべきところお願いします。

2023-02-15 16:33 UTC, yiwiy9 requested changes
細かい指摘もあるけど、確認よろしく。

2023-02-15 16:33 UTC, yiwiy9 commented on frontend/src/routes/entry.tsx
> +          setValue('address1', result.address1 + result.address2 + result.address3)
ここで合体させた住所を返すところまで、`frontend/src/lib/api/suggest-address.ts`でやるか。

理由は、特に今回のアプリでは住所を県・市区町村それぞれを別で使うことはなくて「住所」として使うことしかないから、抽象度高いままにせずにAPIハンドラ側で用途を限定して（住所合体して）良いと思うから。
あと、`type AddressResponse`もAPIハンドラの方で定義したいからってのもある

2023-02-15 16:33 UTC, yiwiy9 commented on frontend/src/routes/entry.tsx
> +import { TEXTURE_IMAGE } from '../config'
すまん、これ入れてかっこよくしてくれたみたいやけど、もっと良いやり方あったから変えたわ。
`main`にマージして、それを参考に変えてみてくれ。

あと、`font-italicSerif`ってクラスも作ったから、試してみたかったら試してみて。イタリックやから登録画面で使えるところなさそうやけど。

2023-02-15 16:33 UTC, yiwiy9 commented on frontend/src/routes/entry.tsx
> +import MainForm from '../components/main-form'
細かいけど、コンポーネントのインポートは`lib/`のインポートより下でやってほしい。
特にルールはないけど、統一感出すために。

2023-02-15 16:33 UTC, yiwiy9 commented on frontend/src/routes/entry.tsx
> +      if (isCorrectFormat) {
これも細かいけど、下のように書いた方がネストが少なくなるから好みかな。
好みの問題やから変更するかは任せるわ。

```ts
if (! isCorrectFormat) throw new Error('zipCode is invalid.')

const zipCode = getValues('zipCode')
// ...
```

2023-02-16 01:25 UTC, fumiya-iwai commented
triggerバリデーション時点ではじかれた場合、`trigger`がエラー設定してくれるから、わざわざ別のエラー投げる必要ないと思った。
それゆえ、`isCorrectFormat`が`true`の時だけに処理書いてる。
あと、今回 try-ctachの構文はなくていけそうやねんけど、あれは必須？

```typescript
const suggestAddressFromZipCode = async () => {
    setIsLoading(true)
    const isCorrectFormat = await trigger('zipCode', { shouldFocus: true })
    if (isCorrectFormat) {
      const zipCode = getValues('zipCode')
      const fullAddress = await suggestAddress(zipCode)
      if (fullAddress) {
        setValue('address1', fullAddress)
      } else {
        setError(
          'zipCode',
          { type: 'custom', message: '住所が取得できませんでした' },
          { shouldFocus: true },
        )
      }
    }
    setIsLoading(false)
  }
```

2023-02-16 10:35 UTC, yiwiy9 requested changes

2023-02-16 10:35 UTC, yiwiy9 commented on frontend/src/lib/api/suggest-address.ts
> +  return null
どっちみち、ネットワークエラーの時にエラーがスローされるから、関数を使用するところでは`try-catch`が必要。
だから、サーバー側のエラーのときもnullを返すんではなくて、throwした方が良い。

`if (!res.ok) throw new Error(res.statusText)`も入れた方が良いかも、これのあとは正常系しか来ないことが保証されてると思うから、typeで`results==null`の場合は考慮不要になると思う。API詳しく見てないけど。

参考
https://zenn.dev/junki555/articles/4ab67fc78ce6

2023-02-16 10:35 UTC, yiwiy9 commented on frontend/src/routes/entry.tsx
> +    if (isCorrectFormat) {
これは確かにこの通りで良いわ。
一点注意が必要なんは、`try-catch`は必要最低限しか囲まんようにすることやな
今回の場合は`const fullAddress = await suggestAddress(zipCode)`以下で良い。（setIsLoading(false)は外）

2023-02-16 17:03 UTC, yiwiy9 approved these changes

2023-02-16 17:03 UTC, merged