Fix form page style
yiwiy9/wedding-invitation pull request #5
Opened 2023-02-21 17:26 UTC by fumiya-iwai

フォームの大きさを全体的に小さくした
ボタンの色変えた
フォーカス中の色変えた

2023-02-21 17:35 UTC, yiwiy9 requested changes
フォントはわざとsanserifのまま？
意図的ならええけど、serifを試してないなら試してみるのもありかも。

2023-02-21 17:35 UTC, yiwiy9 commented on frontend/src/components/children-form.tsx
> +  <div className='text-lg'>
これがあった方が記述量少ない？
これがいるために、`text-base`（デフォルトサイズ）をわざわざ指定せなあかんくなってるんちゃうん？

2023-02-22 09:38 UTC, fumiya-iwai commented
text-lgを初めに書くのをやめた
なんか俺のPCでは勝手にserifになってたから、書いてなかったけど、
一応書いておいた

2023-02-22 14:32 UTC, yiwiy9 approved these changes
Thank you!!!

2023-02-22 14:34 UTC, merged